// schemes.js
document.addEventListener("DOMContentLoaded", () => {
  console.log("Schemes page loaded ✅");
});

function downloadDocs(scheme) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  let title = "";
  let items = [];

  if (scheme === "aby") {
    title = "Atal Bhujal Yojana (ABY) - Required Documents";
    items = [
      "Income Certificate",
      "Aadhaar Card",
      "Property Ownership Proof",
      "Water Tax / Property Tax Receipt"
    ];
  } else if (scheme === "mgnrega") {
    title = "MGNREGA - Required Documents";
    items = [
      "Job Card / MGNREGA Card",
      "Aadhaar Card",
      "Bank Account Passbook",
      "Residence Proof"
    ];
  } else if (scheme === "state") {
    title = "State Subsidy Scheme (Maharashtra) - Required Documents";
    items = [
      "Income Certificate",
      "Caste/Category Certificate",
      "Property Ownership Proof",
      "Water Bill / Tax Receipt"
    ];
  } else if (scheme === "jjm") {
    title = "Jal Jeevan Mission (JJM) - Required Documents";
    items = [
      "Aadhaar Card",
      "Residence Proof (Electricity/Water Bill)",
      "Ration Card or Household ID",
      "Income Certificate",
      "Gram Panchayat Recommendation (for rural applicants)"
    ];
  }

  // PDF content
  doc.setFontSize(16);
  doc.text(title, 20, 30);

  doc.setFontSize(12);
  items.forEach((item, i) => {
    doc.text(`• ${item}`, 20, 60 + i * 20);
  });

  doc.setFontSize(10);
  doc.text("Generated by JalRakshak 1.0", 20, 280);

  // Save file
  doc.save(`${scheme}_required_documents.pdf`);
}
